### ISSUE TITLE
Midea Dongle - Generic MQTT

### ISSUE THREAD

**Issue by njordan77** [reneklootwijk/mideahvac-dongle#2]
Hi Rene, I've following situation, Midea AC and i want/already prepare the Dongle. Only issue that i'm not using HA but Openhab with MQTT.  Sergey ment that its best to not use the current implementation but develop my own code or wait for you as you are in the process to provide a generic Library.

And that is my question: could you PLEASE give me a starting point to control my AC via MQTT. I know pubsubclient...so i would only need to know how i can control the AC via OpenDongle + Arduino IDE (ESP8266 ESP-01). Thanks a lot Norbert

**Comment by iamvlanone** [comment]
Hi, I hope I am not out of line, but I had a look at the article below and could control my AC using MQTT. I am using HA and it was not easy to integrate. So reverted to ESPHome. The author uses OpenHab and provides details on coding using IDE. 

Apologies if you have already seen the article. 

https://community.openhab.org/t/tutorial-connect-your-dumb-midea-ac-unit-to-openhab-with-mqtt/114994

**Comment by reneklootwijk** [comment]
> Sorry Rene to open this threat but i've tried to get in touch with you and could not find any email address via Google. Will remove this communication threat as soon as i can get in touch.
> 
> I've following situation, Midea AC and i want/already prepare the Dongle. Only issue that i'm not using HA but Openhab with MQTT. Sergey ment that its best to not use the current implementation but develop my own code or wait for you as you are in the process to provide a generic Library.
> 
> And that is my question: could you PLEASE give me a starting point to control my AC via MQTT. I know pubsubclient...so i would only need to know how i can control the AC via OpenDongle + Arduino IDE (ESP8266 ESP-01). Thanks a lot Norbert ([norbert.jordan@gmail.com](mailto:norbert.jordan@gmail.com))

I just commited the C library you can use to create your own firmware. However, the documentation is far from finished and correct. See https://github.com/reneklootwijk/midea-uart.

Some time ago I published nodejs code to control an appliance via bridging firmware running on the custom dongle. This code contains a very simple example using MQTT. However, the features implemented in the nodejs code lack the current C library code. The nodejs code can be found here: https://github.com/reneklootwijk/node-mideahvac

**Comment by njordan77** [comment]
Thanks a lot! That is more than i expected to receive in such a short time. i will try both approaches....
